bounds:
  filters1:       [10, 30]
  kernel1:        [2, 3]
  filters2:       [10, 20]
  kernel2:        [2, 3]
  dropout_rate:   [0.1, 0.3]
  dense1:         [32, 64]
  dense2:         [16, 32]
  learning_rate:  [-5, -3]
